# Supabase DB (local 전용 - application.properties 덮어씀)
spring.datasource.url=jdbc:postgresql://aws-1-ap-southeast-2.pooler.supabase.com:6543/postgres?sslmode=require&prepareThreshold=0
spring.datasource.username=postgres.bnjynxwikqspvfimtlja
spring.datasource.password=qkd80wltjs*
